### PR TITLE
Merged from base

### PR DESCRIPTION
**Pull request by d1820**
-Added Exception Node Support
-Added options page (IsEnabledForPublishMembersOnly, UseNaturalLanguageForReturnNode)
-Added CDATA node for return statement for generics

### CODE REVIEW

**Comment by d1820** [comment]
No new Unit tests were added to cover the option scenarios, Some of the current testing needs cleanup, and could not make sense of the Row/Column stuff for currently in the tests, and there was no comments about it.

**Comment by jinyafeng** [comment]
Thanks a lot. You do a good job. I will try to merge when I have time.

**Comment by jinyafeng** [comment]
Hi Friend,

It is hard for me to merge the PR because there are lots of file changes and lots of conflicts.

In this case, I appreciate your precious time and I have two choices for you. Any choice is good for me, please let me know what you think.

1. I add an .editorconfig file to maintain code consistency and make changes to existing files. You can fork again from the latest repository and make your only new features to the new repository. and then create a new Pull Request.  

2. I'm good with you publishing a new version to VS market. But please make a new name and use a new ProductId in code to avoid confusion.

Thanks,

**Comment by jinyafeng** [comment]
> No new Unit tests were added to cover the option scenarios, Some of the current testing needs cleanup, and could not make sense of the Row/Column stuff for currently in the tests, and there was no comments about it.

The Row/Column is used to indicating which row and which line will show warning when there is no XML comment on it. If you give the wrong Row/Column, the unit test will failure.

**Pull request closed without merging**
