### PR TITLE
Converted to VS2022

### PR DESCRIPTION
**Pull request by d1820**
Added support for exception comments
Updated return node to return CDATA for real generic type

### CODE REVIEW

**Comment by jinyafeng** [comment]
Hi  D. Turco,

I have updated my DocumentationAssistant to support VS2022.

I saw you publish an extension "DocumentationAssistant VS2022" also with two good features. That is great.

But I think it is better to push your changes to my repository so we can maintain one extension and give them to all users. What do you think?

Welcome you to contribute code to this repository.

Thanks,

**Comment by d1820** [comment]
Hey!!

if you want to cherry pick those two features into your release I have no
problem taking mine down and just having the one..

I wasn't sure if that was going to be an updated extension or not to VS22
so I probably jumped the gun a little to get something out there but it was
kind of a roadblock for everyone at work cuz we all use your extension...

let me know if you're going to cherry pick those into your release
otherwise I probably would be able to get to creating a PR like next week
sometime





This may have been sent with voice to text, so I apologize for any
misspellings or incorrect wording

**Comment by jinyafeng** [comment]
I think it is better for you to create a PR at any time you like. Let's maintain it together.

**Comment by d1820** [comment]
so I'm looking at your updated master branch in GitHub did you get rid of
the options and being able to select public only?

I still see the source code in the repo, but it looks like the solution
file doesn't have those things anymore so I need to understand what you're
doing before I can try to merge my stuff

This may have been sent with voice to text, so I apologize for any
misspellings or incorrect wording

**Comment by jinyafeng** [comment]
Yes, I have removed the configuration option project.  Because It is not working and I have a new way to implement it. 
The unnecessary source code has been removed, thanks for the reminder.

I will plan to add a .editorConfig file to maintain consistent style.  It is better that we follow the same style and do core and minimum changes.

I saw you adding two features. One is generating exception nodes, this is a good feature to merge.
Another is generating XML CDATA for generic results, Please help me understand it.  And I don't find any source code that will return it.

I think the most situation will be below,
- An array of xxx 
- An list of xxx
- An enumeration of xxx

**Comment by d1820** [comment]
sounds good.

The CDATA is used within XML so you can use greater than and less than
signs as part of the XML object.. so instead of translating the generic
type of the return to a string like you have now it'll actually give you
the full generic type without having to be translated. this covers all
scenarios aside from lists and dictionaries where any response type is
returning a multitude of generic types

so instead of it being

a list of XXX

would be

<![CDATA[List<mytype>]]>

cdata allows you to use <> within xml nodes. at least for teams I've been
on seeing the actual type return is more valuable than seeing a translation
of an inference of a type ie) a list of XXX.

I was thinking of adding an option that would allow the user to say "use
CData for generic return types", maybe defaulting that to true and then
people could turn it off if they wanted to have the text form of a result.

it's not the ideal solution but since Microsoft is adhering strictly to the
XML structure and they don't provide ways to provide greater than less than
signs unless you actually use the Unicode characters which are absolutely
unreadable, cdata is the closet way to accomplish and have it be readable.

does that make sense?


This may have been sent with voice to text, so I apologize for any
misspellings or incorrect wording

**Comment by jinyafeng** [comment]
Thanks, that makes sense.

I also think It is better if we can add a option "use CData for generic return types". But option is not working when I do "Enable for publish members only " option, do you have a good way to implement it? It should be very helpful.

**Comment by d1820** [comment]
I currently have a bunch of changes in play and I have my stuff merged into
your main branch. although I couldn't get your branch to work at all so I
had to recreate a VISX package and basically start over with a valid VS2022
package Right now I'm 4 hours in and I can't get the options to work even
though I'm following the exact same pattern that mads has in his
repositories so if something is still off with this project. I might have
to start the whole thing over from scratch with the shared project. and to
be honest I don't really want to spend that much time on it to try to get
this working right when the stuff that I have works exactly how I want so I
might look at this for a couple more hours over the next few days and if I
can't get it I can send you my branch and you can do what you want with it
but I'll probably move forward with something else. as we both know the
documentation around converting something over to visual studio 2022
absolutely sucks and there's little guidance on it yet so it's kind of a
mess in my opinion.

This may have been sent with voice to text, so I apologize for any
misspellings or incorrect wording

**Comment by d1820** [comment]
so last update of the day .

so I got it all working I got the options page working I got the options
passing across to documentation assistant projects. The problem left is the
package only loads when you load the tools and options so none of the
options are read in at the start of the analyzer. I think this is because
the analyzer runs out of a different context then the UI package so I'm
trying to investigate or figure out a way that we can force load the
options behind the scenes and get access to those values I haven't came
across the way to do that yet All the stuff is in my branch called
return-node-support




This may have been sent with voice to text, so I apologize for any
misspellings or incorrect wording

**Comment by d1820** [comment]
The PR is out there with all the changes. let me know when you have it
published so then I can update mine and then I can pull mine off the
marketplace thanks.

This may have been sent with voice to text, so I apologize for any
misspellings or incorrect wording

**Comment by d1820** [comment]
hey before you merge that in you might want to pull that down I noticed a
bug in there where interfaces are not being documented and your
implementation is not even offered as a option so something seems off
there...



This may have been sent with voice to text, so I apologize for any
misspellings or incorrect wording

**Pull request closed without merging**
